// Package suid embeds the reference lists of setuid/setgid files per
// release (spec §4, W-7) and the sources they are generated from.
//
// A list answers the one question a dpkg database cannot: what mode does the
// distribution ship this file with? dpkg records which package owns a path
// and nothing about its permissions, so without a list every setuid file on
// a Debian-family host would be unverifiable. The list is a floor, never a
// ceiling: it can only vouch for what the image it was generated from
// carried, and the join's version rule (W-7) decides what to do when the
// host has moved on.
//
// The lists are generated by tools/suidindex from sources.json and committed
// here; CI never runs the generator, exactly as docs/reference/stig is
// generated by tools/refindex and read from the committed files. The package
// is deliberately dependency-free and carries no build tag: the collector
// (Linux only) and the maintainer tool both read it, and so does the shape
// test, which must run anywhere.
package suid

import (
	"bytes"
	"cmp"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"slices"
	"strconv"
	"strings"
)

// sourcesName is the generator's input, which lives in this directory but is
// not a list; Load and All must never mistake it for one.
const sourcesName = "sources.json"

//go:embed *.json
var FS embed.FS

// Package is one package a list covers, at the version the image had. A
// package whose maintainer script sets the mode at install time instead of
// shipping it in the archive carries PostinstSetsMode: the archive's own
// mode is then not the truth about an installed host, and the join routes
// its files to walk.suid_sgid_unverified rather than reading the absence of
// a bit as a finding.
type Package struct {
	Name             string `json:"name"`
	Version          string `json:"version"`
	PostinstSetsMode bool   `json:"postinst_sets_mode,omitempty"`
}

// Entry is one file a covered package ships, with the mode, owner and group
// the distribution declares for it. Mode is the numeric POSIX mode masked to
// 0o7777 — 2541 for 0o4755 — the same form internal/facts stores, never the
// decimal spelling of the octal digits.
//
// Every file of every covered package is listed, not only the setuid ones:
// the join must be able to say "this package ships /usr/bin/python3 WITHOUT
// the bit", which an index of setuid files alone could never say.
type Entry struct {
	Path    string `json:"path"`
	Mode    int    `json:"mode"`
	Owner   string `json:"owner"`
	Group   string `json:"group"`
	Package string `json:"package"`
}

// List is one release's reference list. Entries are sorted by path and the
// paths are canonicalised into /usr (pkgfiles.CanonicalUsr) with the image's
// own merged-usr table, so they are already in the form the walk reports.
//
// Arch is the Go architecture name of the image the list was read from
// ("amd64"). A distribution can ship a binary setuid on one architecture and
// not on another, and an image pulled on a different machine is a different
// image, so the list says which one it describes rather than leaving a reader
// to assume.
type List struct {
	Distro      string    `json:"distro"`
	Release     string    `json:"release"`
	Arch        string    `json:"arch"`
	ImageDigest string    `json:"image_digest"`
	Generated   string    `json:"generated"`
	Packages    []Package `json:"packages"`
	Entries     []Entry   `json:"entries"`
}

// Load returns the list for one release, named from the host's os-release ID
// and VERSION_ID ("ubuntu", "22.04" -> ubuntu-22.04.json). When there is no
// list for the exact version it falls back, in order, to <id>-<major>.json
// and then to the highest <id>-<major>.<minor>.json present — see listName
// for why the third step is the one the RHEL family depends on. A release no
// name reaches is (nil, false, nil) — an ordinary answer, which the join
// reports as reference "none" — while a file that will not decode is an
// error naming it.
func Load(id, versionID string) (*List, bool, error) { return loadFrom(FS, id, versionID) }

// All returns every committed list, in file-name order, for the shape test
// and for tools/suidindex -check.
func All() ([]List, error) { return allFrom(FS) }

// Package reports what the list says about one package. The covered
// packages are a curated few dozen, so this is a scan, not an index.
func (l *List) Package(name string) (Package, bool) {
	for _, p := range l.Packages {
		if p.Name == name {
			return p, true
		}
	}
	return Package{}, false
}

// Entry reports what the list declares for one path. Entries are sorted by
// path (listProblems enforces it for every committed list), so the lookup is
// a binary search over a list that can hold tens of thousands of files.
func (l *List) Entry(p string) (Entry, bool) {
	i, ok := slices.BinarySearchFunc(l.Entries, p, func(e Entry, target string) int {
		return strings.Compare(e.Path, target)
	})
	if !ok {
		return Entry{}, false
	}
	return l.Entries[i], true
}

func loadFrom(fsys fs.FS, id, versionID string) (*List, bool, error) {
	if id == "" || versionID == "" {
		return nil, false, nil
	}
	// No pair of a distro and a version spells sources.json, so there is no
	// guard against it here; allFrom, which reads whatever is in the
	// directory, is where the skip belongs.
	name, ok := listName(fsys, id, versionID)
	if !ok {
		return nil, false, nil
	}
	data, err := fs.ReadFile(fsys, name)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, fmt.Errorf("%s: %w", name, err)
	}
	var l List
	if err := json.Unmarshal(data, &l); err != nil {
		return nil, false, fmt.Errorf("%s: %w", name, err)
	}
	return &l, true, nil
}

// listName resolves a host's ID and VERSION_ID to a committed file, in three
// steps (ruling A-36, as amended):
//
//  1. <id>-<versionID>.json   the list generated for exactly this version
//  2. <id>-<major>.json       a list the maintainer pinned to the major
//  3. <id>-<major>.<minor>.json, the highest minor present
//
// Step 3 is what makes the RHEL family work at all. Those images report a
// point release, so the committed files are rocky-9.8.json and
// almalinux-9.8.json; a host running 9.5 matches neither step 1 nor step 2,
// and without step 3 every packaged candidate on it would read reference
// "none". The list is a floor and not a ceiling (see the package comment):
// what it shows carrying a bit is a declaration whatever the version, and
// what it does not is decided by the join's own version rule, which reports
// version_mismatch rather than a finding.
//
// The minors are compared as NUMBERS, component by component, so 9.10 beats
// 9.9 — a string sort gets that backwards — and the answer cannot depend on
// the order the directory is read in.
func listName(fsys fs.FS, id, versionID string) (string, bool) {
	exact := id + "-" + versionID + ".json"
	if fileExists(fsys, exact) {
		return exact, true
	}
	major := versionID
	if i := strings.IndexByte(versionID, '.'); i >= 0 {
		major = versionID[:i]
	}
	if major == "" {
		return "", false
	}
	if name := id + "-" + major + ".json"; name != exact && fileExists(fsys, name) {
		return name, true
	}
	prefix := id + "-" + major + "."
	entries, err := fs.ReadDir(fsys, ".")
	if err != nil {
		return "", false
	}
	best, bestVer := "", []string(nil)
	for _, e := range entries {
		n := e.Name()
		if n == sourcesName || e.IsDir() || !strings.HasPrefix(n, prefix) || !strings.HasSuffix(n, ".json") {
			continue
		}
		ver := strings.Split(strings.TrimSuffix(strings.TrimPrefix(n, id+"-"), ".json"), ".")
		if best == "" || compareVersion(ver, bestVer) > 0 {
			best, bestVer = n, ver
		}
	}
	return best, best != ""
}

// compareVersion orders two dotted versions component by component. A pair
// that are both numbers is compared as numbers; anything else falls back to
// a string comparison, so a component nobody anticipated still orders
// deterministically instead of panicking or being dropped.
func compareVersion(a, b []string) int {
	for i := 0; i < len(a) && i < len(b); i++ {
		na, erra := strconv.Atoi(a[i])
		nb, errb := strconv.Atoi(b[i])
		if erra == nil && errb == nil {
			if na != nb {
				return cmp.Compare(na, nb)
			}
			continue
		}
		if c := strings.Compare(a[i], b[i]); c != 0 {
			return c
		}
	}
	return cmp.Compare(len(a), len(b))
}

func fileExists(fsys fs.FS, name string) bool {
	f, err := fsys.Open(name)
	if err != nil {
		return false
	}
	_ = f.Close()
	return true
}

func allFrom(fsys fs.FS) ([]List, error) {
	names, err := fs.Glob(fsys, "*.json")
	if err != nil {
		return nil, err
	}
	slices.Sort(names)
	out := make([]List, 0, len(names))
	for _, name := range names {
		if name == sourcesName {
			continue
		}
		data, err := fs.ReadFile(fsys, name)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		var l List
		if err := json.Unmarshal(data, &l); err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		out = append(out, l)
	}
	return out, nil
}

// --- the generator's input ----------------------------------------------

// Sources is sources.json: per release, the public image the list is
// generated inside and the packages it covers. tools/suidindex reads it;
// nothing at run time does.
//
// Note carries what a comment would carry if JSON had comments — above all
// that the packages listed here are a SEED and not the whole covered set:
// the generator unions them with the owners of every setuid and setgid file
// the image carries, so a list covers packages this file never names.
type Sources struct {
	Note     string    `json:"note,omitempty"`
	Releases []Release `json:"releases"`
}

// Release pins one image by name AND by digest, so a regeneration months
// later reads the same bytes the committed list was made from — the rule
// tools/refindex/sources.json follows for the DISA files.
type Release struct {
	ID        string          `json:"id"`
	VersionID string          `json:"version_id"`
	Image     string          `json:"image"`
	Digest    string          `json:"digest"`
	Packages  []SourcePackage `json:"packages"`
}

// SourcePackage is one covered package and why it is covered. A package the
// image itself installs is read inside the image and needs no URL; an
// extended package — one a base image does not carry but a server host does
// — is downloaded from a snapshot service and pins both the URL and the
// SHA-256, so -check cannot drift with the live archive.
type SourcePackage struct {
	Name             string `json:"name"`
	Reason           string `json:"reason"`
	URL              string `json:"url,omitempty"`
	SHA256           string `json:"sha256,omitempty"`
	PostinstSetsMode bool   `json:"postinst_sets_mode,omitempty"`
}

// LoadSources decodes the committed sources.json strictly: an unknown field
// is an error, so a typo in a hand-edited entry cannot silently drop a
// package from the generator's input.
func LoadSources() (*Sources, error) {
	data, err := FS.ReadFile(sourcesName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", sourcesName, err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var s Sources
	if err := dec.Decode(&s); err != nil {
		return nil, fmt.Errorf("%s: %w", sourcesName, err)
	}
	return &s, nil
}
