// Package suid embeds the reference lists of setuid/setgid files per
// release (spec §4, W-7) and the sources they are generated from.
//
// A list answers the one question a dpkg database cannot: what mode does the
// distribution ship this file with? dpkg records which package owns a path
// and nothing about its permissions, so without a list every setuid file on
// a Debian-family host would be unverifiable. The list is a floor, never a
// ceiling: it can only vouch for what the image it was generated from
// carried, and the join's version rule (W-7) decides what to do when the
// host has moved on.
//
// The lists are generated by tools/suidindex from sources.json and committed
// here; CI never runs the generator, exactly as docs/reference/stig is
// generated by tools/refindex and read from the committed files. The package
// is deliberately dependency-free and carries no build tag: the collector
// (Linux only) and the maintainer tool both read it, and so does the shape
// test, which must run anywhere.
package suid

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"slices"
	"strings"
)

// sourcesName is the generator's input, which lives in this directory but is
// not a list; Load and All must never mistake it for one.
const sourcesName = "sources.json"

//go:embed *.json
var FS embed.FS

// Package is one package a list covers, at the version the image had. A
// package whose maintainer script sets the mode at install time instead of
// shipping it in the archive carries PostinstSetsMode: the archive's own
// mode is then not the truth about an installed host, and the join routes
// its files to walk.suid_sgid_unverified rather than reading the absence of
// a bit as a finding.
type Package struct {
	Name             string `json:"name"`
	Version          string `json:"version"`
	PostinstSetsMode bool   `json:"postinst_sets_mode,omitempty"`
}

// Entry is one file a covered package ships, with the mode, owner and group
// the distribution declares for it. Mode is the numeric POSIX mode masked to
// 0o7777 — 2541 for 0o4755 — the same form internal/facts stores, never the
// decimal spelling of the octal digits.
//
// Every file of every covered package is listed, not only the setuid ones:
// the join must be able to say "this package ships /usr/bin/python3 WITHOUT
// the bit", which an index of setuid files alone could never say.
type Entry struct {
	Path    string `json:"path"`
	Mode    int    `json:"mode"`
	Owner   string `json:"owner"`
	Group   string `json:"group"`
	Package string `json:"package"`
}

// List is one release's reference list. Entries are sorted by path and the
// paths are canonicalised into /usr (pkgfiles.CanonicalUsr) with the image's
// own merged-usr table, so they are already in the form the walk reports.
type List struct {
	Distro      string    `json:"distro"`
	Release     string    `json:"release"`
	ImageDigest string    `json:"image_digest"`
	Generated   string    `json:"generated"`
	Packages    []Package `json:"packages"`
	Entries     []Entry   `json:"entries"`
}

// Load returns the list for one release, named from the host's
// os-release ID and VERSION_ID ("ubuntu", "22.04" -> ubuntu-22.04.json). A
// release with no committed list is (nil, false, nil) — an ordinary answer,
// which the join reports as reference "none" — while a file that will not
// decode is an error naming it.
func Load(id, versionID string) (*List, bool, error) { return loadFrom(FS, id, versionID) }

// All returns every committed list, in file-name order, for the shape test
// and for tools/suidindex -check.
func All() ([]List, error) { return allFrom(FS) }

// Package reports what the list says about one package. The covered
// packages are a curated few dozen, so this is a scan, not an index.
func (l *List) Package(name string) (Package, bool) {
	for _, p := range l.Packages {
		if p.Name == name {
			return p, true
		}
	}
	return Package{}, false
}

// Entry reports what the list declares for one path. Entries are sorted by
// path (listProblems enforces it for every committed list), so the lookup is
// a binary search over a list that can hold tens of thousands of files.
func (l *List) Entry(p string) (Entry, bool) {
	i, ok := slices.BinarySearchFunc(l.Entries, p, func(e Entry, target string) int {
		return strings.Compare(e.Path, target)
	})
	if !ok {
		return Entry{}, false
	}
	return l.Entries[i], true
}

func loadFrom(fsys fs.FS, id, versionID string) (*List, bool, error) {
	if id == "" || versionID == "" {
		return nil, false, nil
	}
	name := id + "-" + versionID + ".json"
	if name == sourcesName {
		return nil, false, nil
	}
	data, err := fs.ReadFile(fsys, name)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, fmt.Errorf("%s: %w", name, err)
	}
	var l List
	if err := json.Unmarshal(data, &l); err != nil {
		return nil, false, fmt.Errorf("%s: %w", name, err)
	}
	return &l, true, nil
}

func allFrom(fsys fs.FS) ([]List, error) {
	names, err := fs.Glob(fsys, "*.json")
	if err != nil {
		return nil, err
	}
	slices.Sort(names)
	out := make([]List, 0, len(names))
	for _, name := range names {
		if name == sourcesName {
			continue
		}
		data, err := fs.ReadFile(fsys, name)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		var l List
		if err := json.Unmarshal(data, &l); err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		out = append(out, l)
	}
	return out, nil
}

// --- the generator's input ----------------------------------------------

// Sources is sources.json: per release, the public image the list is
// generated inside and the packages it covers. tools/suidindex reads it;
// nothing at run time does.
type Sources struct {
	Releases []Release `json:"releases"`
}

// Release pins one image by name AND by digest, so a regeneration months
// later reads the same bytes the committed list was made from — the rule
// tools/refindex/sources.json follows for the DISA files.
type Release struct {
	ID        string          `json:"id"`
	VersionID string          `json:"version_id"`
	Image     string          `json:"image"`
	Digest    string          `json:"digest"`
	Packages  []SourcePackage `json:"packages"`
}

// SourcePackage is one covered package and why it is covered. A package the
// image itself installs is read inside the image and needs no URL; an
// extended package — one a base image does not carry but a server host does
// — is downloaded from a snapshot service and pins both the URL and the
// SHA-256, so -check cannot drift with the live archive.
type SourcePackage struct {
	Name             string `json:"name"`
	Reason           string `json:"reason"`
	URL              string `json:"url,omitempty"`
	SHA256           string `json:"sha256,omitempty"`
	PostinstSetsMode bool   `json:"postinst_sets_mode,omitempty"`
}

// LoadSources decodes the committed sources.json strictly: an unknown field
// is an error, so a typo in a hand-edited entry cannot silently drop a
// package from the generator's input.
func LoadSources() (*Sources, error) {
	data, err := FS.ReadFile(sourcesName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", sourcesName, err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var s Sources
	if err := dec.Decode(&s); err != nil {
		return nil, fmt.Errorf("%s: %w", sourcesName, err)
	}
	return &s, nil
}
